name: C CI

on:
  push:
  pull_request:

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang]
    env:
      CC: ${{ matrix.compiler }}
    steps:
      - uses: actions/checkout@v4
      - run: $CC --version
      - run: make clean
      - run: make
      - run: make test
      - run: make release
      - if: matrix.compiler == 'clang'
        env:
          ASAN_OPTIONS: detect_leaks=0
          UBSAN_OPTIONS: print_stacktrace=1
        run: make sanitize

  macos:
    runs-on: macos-latest
    env:
      CC: clang
      ASAN_OPTIONS: detect_leaks=0
      UBSAN_OPTIONS: print_stacktrace=1
    steps:
      - uses: actions/checkout@v4
      - run: $CC --version
      - run: make clean
      - run: make
      - run: make test
      - run: make sanitize
      - run: make release
